version: "3.8"

services:
    express:
        build:
            context: ./express-user-service
            dockerfile: ./Dockerfile
        ports:
            - "3001:3001"
        networks:
            - app-network

    fastapi:
        build:
            context: ./fastapi-task-service
            dockerfile: ./Dockerfile
        ports:
            - "8001:8001"
        networks:
            - app-network

    django:
        build:
            context: ./django-main
            dockerfile: ./Dockerfile
        ports:
            - "8000:8000"
        depends_on:
            - express
            - fastapi
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
